#!/bin/bash
#  _   _       _
# | \ | | ___ | |_ ___  ___
# |  \| |/ _ \| __/ _ \/ __|
# | |\  | (_) | ||  __/\__ \
# |_| \_|\___/ \__\___||___/
# Author : Zachary Blundell
# This script is used for opening nextcloud notes and onpening todays note

day_num="$(date +'%d')"
day_name_short="$(date +'%a')" # locale's abbreviated weekday name (e.g., Sun)

month_num="$(date +'%m')"        # 01‑12 (two‑digit, leading zero)
month_name_short="$(date +'%b')" # locale's abbreviated month name (e.g., Jan)

year="$(date +'%Y')" # four‑digit year

month_dir="log/${year}/${month_num}(${month_name_short})"

file_name="${day_num}(${day_name_short})-${month_num}-${year}.md"
file_path="${month_dir}/${file_name}"

echo $file_path

# go to notes dir
cd $HOME/Nextcloud/Notes/
# Verify that the todays note exists
if [[ ! -f "${file_path}" ]]; then
  echo "Error: notes folder '${notes_root}' is missing" >&2
  exit 1
fi
nvim $file_path
# goBack
cd "$OLDPWD"
