#!/bin/bash
#     _   __      __
#    / | / /___  / /____  _____
#   /  |/ / __ \/ __/ _ \/ ___/
#  / /|  / /_/ / /_/  __(__  )
# /_/ |_/\____/\__/\___/____/
# Author : Zachary Blundell
# This script is used for opening nextcloud notes and onpening todays note

day_num="$(date +'%d')"
day_name_short="$(date +'%a')" # locale's abbreviated weekday name (e.g., Sun)

month_num="$(date +'%m')"        # 01‑12 (two‑digit, leading zero)
month_name_short="$(date +'%b')" # locale's abbreviated month name (e.g., Jan)

year="$(date +'%Y')" # four‑digit year

month_dir="log/${year}/${month_num}(${month_name_short})"

file_name="${day_num}(${day_name_short})-${month_num}-${year}.md"
file_path="${month_dir}/${file_name}"

echo $file_path

# go to notes dir
cd $HOME/Nextcloud/Notes/

# Verify that the todays note exists i.e. created by the server daily_note script
if [[ ! -f "${file_path}" ]]; then
  echo "Error: notes folder '${file_path}' is missing" >&2
  sleep 1
  nvim .
else
  nvim $file_path
fi

# goBack
cd "$OLDPWD"
